[package]
authors = ["Josiah Putman <joshikatsu@gmail.com>"]
edition = "2018"
name = "simple"
version = "0.1.0"

[dependencies]
colored = "2.0.0"
kataru = {path = "../.."}
lazy_static = "1.4.0"
regex = "1.4.3"
linear-map = "1.2.0"

[build-dependencies]
kataru = {path = "../.."}
